import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Header from '../components/header'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SuchiCreates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <Header />
          <main className="min-h-screen">{children}</main>
          <footer className="bg-orange-600 py-12">
            <div className="container mx-auto px-4 text-center text-black">
              <p>Suchi Creates</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
